keys:
  - &admin_khaneliman age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_khaneliman
  - path_regex: secrets/khanelinix/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_khaneliman
